Stack_Learn/Models/Curso.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Stack_Learn.Models
{
    public class Curso
    {
        public long CursoId { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public int Qtd_Aulas { get; set; }
        public double Preco { get; set; }
        
        public long? ProfessorId { get; set; }
        public long? CategoriaId { get; set; }

        public Categoria Categoria { get; set; }
        public Professor Professor { get; set; }

        public virtual ICollection<Aula> Aulas { get; set; }
    }
}

Stack_Learn/Models/MeusCursosIndex.cs
using Modelos.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Stack_Learn.Models
{
    public class MeusCursosIndex
    {
        public List<Curso> em_andamento { get; set; }
        public List<Curso> concluido { get; set; }

        public long? MeusCursosIndexId { get; set; }
    }
}

Stack_Learn/Controllers/AvaliacoesController.cs
using Stack_Learn.Context;
using Modelos.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Stack_Learn.Controllers
{
    public class AvaliacoesController : Controller
    {
        private EFContext context = new EFContext();

        [Authorize(Roles = "ADM")]
        public ActionResult Index()
        {
            return View(context.Avaliacoes.Include(c => c.Curso).Include(a=>a.Aluno).OrderBy(c => c.Nota));
        }
        [Authorize(Roles = "Aluno")]
        public ActionResult Create()
        {

            ViewBag.IdCurso = Request.QueryString["CursoId"];
            ViewBag.IdAluno = Request.QueryString["AlunoId"];
            ViewBag.NomeCurso = context.Cursos.OrderBy(b => b.Nome);
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Avaliacao avaliacao)
        {

            /*
            avaliacao.AlunoNome = context.Alunos.Where(a => a.AlunoId == avaliacao.AlunoId).First().Nome;//adicionar manualmente o nome do aluno, se editar não vai editar aqui também :/
            avaliacao.Curso.Nome = context.Cursos.Where(a => a.CursoId == avaliacao.CursoId).First().Nome;//adicionar manualmente o nome do curso, objetos vem nulos
            avaliacao.curso_usuario.AlunoId = avaliacao.AlunoId;
            
            if (ModelState.IsValid)
            {
                context.Entry(avaliacao).State = EntityState.Modified;
                avaliacao.AlunoNome = context.Alunos.Where(a => a.AlunoId == avaliacao.AlunoId).First().Nome;//adicionar manualmente o nome do aluno, se editar não vai editar aqui também :/
                avaliacao.Curso.Nome = context.Cursos.Where(a => a.CursoId == avaliacao.CursoId).First().Nome;//adicionar manualmente o nome do curso, objetos vem nulos
                avaliacao.curso_usuario.AlunoId = avaliacao.AlunoId;
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            //se estiver vazio, volta de boa
            Avaliacao avaliacaooo = context.Avaliacoes.Find(avaliacao.AvaliacaoId);
            context.Avaliacoes.Remove(avaliacaooo);
            context.SaveChanges();
            return View("MeusCursosIndex");
            */
            avaliacao.AlunoNome = context.Alunos.Where(a => a.AlunoId == avaliacao.AlunoId).First().Nome;//adicionar manualmente o nome do aluno, se editar não vai editar aqui também :/
            avaliacao.Data_hora = DateTime.Now;
            context.Avaliacoes.Add(avaliacao);
            context.SaveChanges();
            return RedirectToAction("../Cursos/MeusCursosIndex/" + avaliacao.AlunoId);
        }

        [Authorize(Roles = "ADM")]
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Avaliacao avaliacao = context.Avaliacoes.Find(id);
            if (avaliacao == null)
            {
                return HttpNotFound();
            }
            ViewBag.CursoId = new SelectList(context.Cursos.OrderBy(b => b.Nome), "CursoId", "Nome", avaliacao.Curso);
            ViewBag.AlunoId = new SelectList(context.Alunos.OrderBy(b => b.Nome), "AlunoId", "Nome", avaliacao.Aluno);
            return View(avaliacao);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Avaliacao avaliacao)
        {
            if (ModelState.IsValid)
            {
                avaliacao.AlunoNome = context.Alunos.Where(a => a.AlunoId == avaliacao.AlunoId).First().Nome;//adicionar manualmente o nome do aluno
                context.Entry(avaliacao).State = EntityState.Modified;
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(avaliacao);
        }
        [Authorize(Roles = "ADM")]
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Avaliacao avaliacao = context.Avaliacoes.Where(p => p.AvaliacaoId == id).Include(c => c.Curso).Include(f => f.Aluno).First();
            if (avaliacao == null)
            {
                return HttpNotFound();
            }
            return View(avaliacao);
        }
        [Authorize(Roles = "ADM")]
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Avaliacao avaliacao = context.Avaliacoes.Find(id);
            if (avaliacao == null)
            {
                return HttpNotFound();
            }
            return View(avaliacao);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(long id)
        {
            Avaliacao avaliacao = context.Avaliacoes.Find(id);
            context.Avaliacoes.Remove(avaliacao);
            context.SaveChanges();
            TempData["Message"] = "Avaliacao " + avaliacao.Nota + " foi removida";
            return RedirectToAction("Index");
        }
    }
}

Stack_Learn/Controllers/CursosController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Stack_Learn.Context;
using Modelos.Models;
using System.IO;
using Stack_Learn.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Stack_Learn.Areas.Seguranca.Models;
using Stack_Learn.Infraestrutura;

namespace Stack_Learn.Controllers
{
    public class CursosController : Controller
    {

        private EFContext context = new EFContext();

        private GerenciadorUsuario GerenciadorUsuario
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<GerenciadorUsuario>();
            }
        }

        private void PopularViewBag(Curso curso = null)
        {
            if (curso == null)
            {
                ViewBag.CategoriaId = new SelectList(context.Categorias.OrderBy(b => b.Nome), "CategoriaId", "Nome", curso.CategoriaId);
                ViewBag.ProfessorId = new SelectList(context.Professores.OrderBy(b => b.Nome), "ProfessorId", "Nome", curso.ProfessorId);
            }
            else
            {
                ViewBag.CategoriaId = new SelectList(context.Categorias.OrderBy(b => b.Nome), "CategoriaId", "Nome", curso.CategoriaId);
                ViewBag.ProfessorId = new SelectList(context.Professores.OrderBy(b => b.Nome), "ProfessorId", "Nome", curso.ProfessorId);
            }


        }
        private byte[] SetLogotipo(HttpPostedFileBase logotipo)
        {
            var bytesLogotipo = new byte[logotipo.ContentLength];
            logotipo.InputStream.Read(bytesLogotipo, 0, logotipo.ContentLength);
            return bytesLogotipo;
        }
        public FileContentResult GetLogotipo(long id)
        {
            Curso curso = context.Cursos.Where(p => p.CursoId == id).Include(c => c.Categoria).Include(f => f.Professor).First();
            if (curso != null)
            {
                if (curso.NomeArquivo != null)
                {
                    var bytesLogotipo = new byte[curso.TamanhoArquivo];
                    FileStream fileStream = new FileStream(Server.MapPath("~/App_Data/" + curso.NomeArquivo), FileMode.Open, FileAccess.Read);
                    fileStream.Read(bytesLogotipo, 0, (int)curso.TamanhoArquivo);
                    return File(bytesLogotipo, curso.LogotipoMimeType);
                }
            }
            return null;
        }
        public ActionResult DownloadArquivo(long id)
        {

            Curso curso = context.Cursos.Where(p => p.CursoId == id).Include(c => c.Categoria).Include(f => f.Professor).First();
            FileStream fileStream = new FileStream(Server.MapPath("~/App_Data/" + curso.NomeArquivo), FileMode.Open, FileAccess.Read);
            return File(fileStream.Name, curso.LogotipoMimeType, curso.NomeArquivo);

        }
        private ActionResult GravarCurso(Curso curso, HttpPostedFileBase logotipo, string chkRemoverImagem)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (chkRemoverImagem != null)
                    {
                        curso.Logotipo = null;
                    }
                    if (logotipo != null)
                    {
                        curso.LogotipoMimeType = logotipo.ContentType;
                        curso.Logotipo = SetLogotipo(logotipo);
                        curso.NomeArquivo = logotipo.FileName;
                        curso.TamanhoArquivo = logotipo.ContentLength;

                        string strFileName = Server.MapPath("~/App_Data/") + Path.GetFileName(logotipo.FileName);
                        logotipo.SaveAs(strFileName);
                    }
                    if (curso.CursoId == null)
                    {
                        context.Cursos.Add(curso);
                    }
                    else
                    {
                        context.Entry(curso).State = EntityState.Modified;
                    }
                    context.SaveChanges();
                    return RedirectToAction("Index");
                }
                PopularViewBag(curso);
                return View(curso);
            }
            catch
            {
                PopularViewBag(curso);
                return View(curso);
            }
        }
        [Authorize(Roles = "ADM")]
        public ActionResult Index()
        {
            return View(context.Cursos.Include(c => c.Categoria).Include(f => f.Professor).OrderBy(n => n.Nome));
        }
        public ActionResult Lista()//get, sem post
        {
            var Cursos_Usuarios = new CursosUsuarios();
            if (System.Web.HttpContext.Current.User.Identity.Name.ToString() != "")
            {
                var userid = System.Web.HttpContext.Current.User.Identity.GetUserId();
                Usuario user = GerenciadorUsuario.FindById(userid);
                Cursos_Usuarios.AlunoId = user.AlunoId;
            }
            var Cursos_totais = new List<Curso>();
            foreach (var item in context.Cursos.Include(c => c.Categoria).Include(f => f.Professor).OrderBy(n => n.Nome))
            {
                Cursos_totais.Add(item);
            }
            Cursos_Usuarios.Cursos = Cursos_totais;

            var Categorias_totais = new List<Categoria>();
            foreach (var item in context.Categorias.OrderBy(c => c.Nome))
            {
                Categorias_totais.Add(item);
            }
            Cursos_Usuarios.Categorias = Categorias_totais;
            return View(Cursos_Usuarios);
        }
        [Authorize(Roles = "Aluno")]
        public ActionResult MeusCursosIndex(long? id)
        {
            //aluno -> pedido ok -> curso ok
            long? AlunoId = id;//sempre o primeiro
            List<Curso> concluidoo = new List<Curso>();
            List<Curso> emm_andamento = new List<Curso>();

            IQueryable<Curso> todos = context.Cursos.Include(c => c.Categoria).Include(f => f.Professor).OrderBy(n => n.Nome);

            foreach (Curso item in todos)
            {
                int concluidos = 0;
                int percorrer_list = item.Qtd_Aulas ;//2
                int list_final = 0;//0 1 2 

                foreach(Aula subitem in item.Aulas)
                {
                    if(subitem.AlunoId == AlunoId)
                    {
                        list_final++;//1 2 3
                        if (subitem.TrueFalse == true)
                        {
                            concluidos++;//1
                        }
                        if (list_final == percorrer_list || list_final == item.Aulas.Count)//tem todas as aulas para serem analisadas x se só tem uma
                        {
                            if (concluidos < percorrer_list)
                            {
                                emm_andamento.Add(item);
                            }
                            if (concluidos == percorrer_list)
                            {
                                concluidoo.Add(item);
                            }
                        }
                    }
                }
            }

            MeusCursosIndex index = new MeusCursosIndex();
            index.em_andamento = emm_andamento;
            index.concluido = concluidoo;
            index.MeusCursosIndexId = AlunoId;
            return View(index);


       }
        [Authorize(Roles = "ADM")]
        public ActionResult Create()
        {
            //para quem comprar, vir com todos os cursos falso
            ViewBag.CategoriaId = new SelectList(context.Categorias.OrderBy(b => b.Nome),"CategoriaId", "Nome");
            ViewBag.ProfessorId = new SelectList(context.Professores.OrderBy(b => b.Nome),"ProfessorId", "Nome");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Curso curso)
        {
            
            if (curso.Professor != null)
            {
                curso.NomeProfessor = curso.Professor.Nome;
            }
            else
            {
                curso.NomeProfessor = "Sem Professor";
            }
            context.Cursos.Add(curso);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        [Authorize(Roles = "ADM")]
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Curso curso = context.Cursos.Find(id);
            if (curso == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoriaId = new SelectList(context.Categorias.OrderBy(b => b.Nome), "CategoriaId","Nome", curso.CategoriaId);
            ViewBag.ProfessorId = new SelectList(context.Professores.OrderBy(b => b.Nome), "ProfessorId","Nome", curso.ProfessorId);
            return View(curso);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Curso curso, HttpPostedFileBase logotipo = null, string chkRemoverImagem = null)
        {
            return GravarCurso(curso, logotipo, chkRemoverImagem);
        }

        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Curso curso = context.Cursos.Where(p => p.CursoId == id).Include(c => c.Categoria).Include(f => f.Professor).First();
            if (curso == null)
            {
                return HttpNotFound();
            }
            CursoDetails objeto = new CursoDetails();
            objeto.curso = curso;
            objeto.cursos = context.Cursos.Include(c => c.Categoria).Include(f => f.Professor).OrderBy(n => n.Nome);
            
            var Cursos_Usuarios = new CursosUsuarios();

Stack_Learn/Views/Cursos/Lista.cshtml
@model Modelos.Models.CursosUsuarios
@using Stack_Learn.Infraestrutura
@{
    Layout = null;
    int verificar = 0;
}
<head>
    <title>Stack Learn | Lista cursos online</title>
    <link href="@Url.Content("~/Css/PaginasInternas.css")" rel="stylesheet" />
    <style>
        .filter-btn {
            background: transparent;
            font-family: 'Jost';
            font-size: 16px;
            font-weight: 400;
            color: white;
            text-align: right;
            border: none;
            margin: 12px;
        }

        .filter-btn:hover, .filter-btn.active {
            border-bottom: 1px solid white;
            
            }
    </style>
</head>
<body>
    @{
        if (Html.GetAuthenticatedUser().ToString() != "")
        {
            @Html.Partial("~/Views/Shared/_Header_Aluno.cshtml", Model)
        }
        else
        {
            @Html.Partial("~/Views/Shared/_Header_Sem_Login.cshtml", Model)
        }
    }
    <h1 class="fontJost400" style="background-color:#FFCC36; margin-top:0px; font-size:22px; text-align:center; padding: 1.5em; ">EXPLORAR CURSOS</h1>

    <div class="flex-col space-around" style="margin-bottom:4em;">
        <div class="flex-column" style="border-radius: 5px; background-color: #515352; width: 280px; margin-top: 16px; height: 350px;">
            <h2 class="fontJost700" style="color:white;margin-left:2em;">Categorias</h2>
            <button class="main-btn filter-btn active" id="all-btn">Todos</button>
            @for (int i = 0; i < Model.Categorias.Count; i++)
            {
                <button class="main-btn filter-btn" id="@Model.Categorias[i].Nome-btn">@Model.Categorias[i].Nome</button>
            }


        </div>

        <div class="parte1-2 flex-col center-justify" style="margin-bottom: 2em; width:100%; height: 100%; flex-wrap: wrap; padding: 10px;">

            @foreach (var item in Model.Cursos)
            {
                <div class="project-box @item.Categoria.Nome">
                    <a href="/Cursos/Details/@item.CursoId" class="flex-column center space-around" style="
                    padding: 2em;
                    width: 225px;
                    height: 300px;
                    border: 3px solid transparent;
                    box-shadow: 2px 1000px 1px #ffff inset;
                    background-image: linear-gradient(to right, #70D7C7, #FFCB34);
                    color: black;
                    margin: 16px 12px 0px 12px;
                    border-radius: 20px;

            ">
                        <img src="@Url.Action("GetLogotipo", "Cursos", new { id = item.CursoId })" height="150" width="150" style="margin: 12px 0;" />
                        <h3 class="fontJost400" style="height: 200px; text-align:center;">@item.Nome.ToUpper()</h3>
                        <h3 class="fontJost400" style="background-color:#FFCC36; padding: 5px;">R$ @item.Preco</h3>
                    </a>
                </div>

            }
        </div>

        <div class="flex-column" style="border-radius:5px;background-color:#515352; height: 540px;">
            <h2 class="fontJost700" style="color:white;margin-left:2em; margin-top: 16px;">Destaques do mes</h2>
            @foreach (var item in Model.Cursos)
            {
                verificar++;
                if (verificar < 4)
                {
                    <div class="flex-col center" style="color:#515352; margin-left:2em; margin-bottom: 2em;">
                        <img src="@Url.Action("GetLogotipo", "Cursos", new { id = item.CursoId })" height="125" width="100" />
                        <h3 class="fontJost400" style="color:white; margin-left: 12px; margin-bottom: 12px; width: 140px;">@item.Nome.ToUpper()</h3>
                    </div>
                }
                if(verificar >= 4)
                {
                    break;
                }
            }
        </div>
    </div>
    @Html.Partial("~/Views/Shared/_Footer.cshtml", Model)
    <script src="~/Scripts/scripts/filtro.js"></script>
</body>
@section ScriptPage{
    <script src="@Url.Content("~/scripts/DataTables-1.10.2/jquery.dataTables.js")"></script>
    <script src="@Url.Content("~/scripts/DataTables-1.10.2/dataTables.bootstrap.js")"></script>
}

Stack_Learn/Views/Cursos/MeusCursosIndex.cshtml
@model Stack_Learn.Models.MeusCursosIndex
@using Stack_Learn.Infraestrutura
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Stack Learn | Meus cursos index</title>
    <link href="@Url.Content("~/Css/PaginasInternas.css")" rel="stylesheet" />
</head>
<body>
    <div class="panel-footer panel-info flex center color-bg">
        <a href="/Home/PaginaInicial"> <img src="~/img/logo2.svg" /> </a>
        <div class="flex-col center fontJost400" style="font-size: 20px;">
            @if (Model.MeusCursosIndexId == 0)
            {
                <a href="#" class="linkPaginas" id="aMeusCursos">Meus cursos</a>
            }
            <a href="/Cursos/MeusCursosIndex/@Model.MeusCursosIndexId" class="linkPaginas" id="aMeusCursos">Meus cursos</a>
            <a href="/Cursos/Lista" class="linkPaginas" id="aCursos">Cursos</a>
            <a href="#" class="linkPaginas" id="aAssinatura">Assinatura</a>
        </div>
        <div class="flex-col center fontJost400">
            <a>
                <img src="~/img/foto_estudantefoto.svg" height="40" width="40" />
            </a>
            @Html.GetAuthenticatedUser().ToString().ToUpper()
            @Html.ActionLink(" - Sair", "Logout", "Account")
            <a>
                <img src="~/img/carrinho.svg" height="40" width="40" />
            </a>
        </div>
    </div>

    <h1 class="fontJost400" style="background-color:#FFCC36; margin-top:0px; font-size:22px; text-align:center; padding: 1.5em; ">EXPLORAR CURSOS</h1>
    <div class="part1 flex-column " style="padding: 1em; flex-wrap: wrap; width: 100%; width: 50%; margin: 0 auto;">
        <h1 class="fontJost400" style="font-size: 26px; font-weight: 500; margin: 0px 0px 10px 0px;text-align: left;">EM ANDAMENTO</h1>
        <div class="flex-col " style="flex-wrap: wrap;">
            @foreach (var item in Model.em_andamento)
            {
                <div class="card part1 flex-col" style="
            border: 3px solid transparent;
            box-shadow: 2px 1000px 1px #ffff inset;
            background-image: linear-gradient(to right, #70D7C7, #FFCB34);
            color: black;
            margin: 12px 20px 0px 0px;
            padding: 16px;
">
                    @{
                        int aulasfeitas = 0;
                        int progresso = 0;


                        foreach (var subitem in item.Aulas)
                        {
                            if (subitem.TrueFalse == true)
                            {
                                aulasfeitas++;
                            }
                        }
                        progresso = (aulasfeitas * 100) / item.Qtd_Aulas;

                        int tamanho = item.Categoria.Nome.Length;
                        <div class="esquerda flex-column">
                            <a style="
                        font-family:'Jost';
                        font-size: 14px;
                        font-style: normal;
                        font-weight: 300;
                        text-decoration: none;
                        border: 1px solid #ECE8EF;
                        border-radius: 5px;
                        color: black;
                        width: calc(10px*@tamanho);">@item.Categoria.Nome.ToUpper()</a>
                        <h3 style="font-family:'Jost'; font-size: 16px;">@item.Nome</h3>
                        @Html.HiddenFor(m => item.LogotipoMimeType)
                        @Html.HiddenFor(m => item.Logotipo)
                        @Html.HiddenFor(m => item.NomeArquivo)
                        @Html.HiddenFor(m => item.TamanhoArquivo)
                        <img src="@Url.Action("GetLogotipo", "Cursos", new { id = item.CursoId })" width="150" height="80" />




                    </div>


                    <div class="direita flex-column" style="
                align-items:center;
                justify-content: flex-end;
                margin-left: 10px;

                   ">
                        <h4 style="
                    border-radius: 1000%;
                    background-color:#70D7C7;
                    padding: 8px;
                    font-family: 'Jost';
                    font-size:16px;
                    ">
                            @progresso%
                        </h4>


                        @foreach (var subitem in item.Aulas)
                        {
                            long? AulaaId = 0;
                            if (subitem.CursoId == item.CursoId && subitem.AlunoId == Model.MeusCursosIndexId)
                            {
                                AulaaId = subitem.AulaId;
                                <h4 style="
                        background-color:#FFCC36;
                        padding: 10px;
                        font-family: 'Jost';
                        color: black;
                        font-size: 16px;
                        margin: 0px;
                        border-radius: 5px;
                        ">
                                    <a href="/Aulas/AulaIndividual/@AulaaId" style="color:black;">Continuar Aulas</a>

                                </h4>
                                break;
                            }

                        }
                    </div>

                    }

                </div>
            }

        </div>
    </div>

    <div class="outside part 2" style=" background-color: #515352">
        <div class="button-wrap flex-col space-between" style="z-index: 10; padding: 10px 400px; top: 300px; position: relative">
            <button class="arrow text" id="arrow-left" onclick="slideLeft()" style="background: #515352; border: none;">
                <span style="
            color: white;
            font-size: 40px;
            ">&#10094;</span>
            </button>
            <button class="arrow" id="arrow-right" onclick="slideRight()" style="background: #515352; border: none;">
                <span style="
            color: white;
            font-size: 40px;">&#10095;</span>
            </button>
        </div>
        <div class="part 2 flex-column" style="background-color:#515352;padding: 1em; flex-wrap: wrap; width: 50%; margin: 0 auto;">
            <h1 class="fontJost400" style="font-size: 26px;color: white; margin: 0px 0px 15px 0px;">CONCLUIDO</h1>

            <div class="carrosel flex-col" style="flex-wrap: wrap; overflow: hidden; height: 442px;">


                @foreach (var item in Model.concluido)
                {
                    <div class=" slide" style="width: 100%;">
                        <div class=" card part 2 flex-col space-between" style="
                border: 1px solid transparent;
                box-shadow: 2px 1000px 1px #ffff inset;
                background-image: linear-gradient(to right, #70D7C7, #FFCB34);
                color: black;
                padding: 1em;
                width: 100%;

                ">

                            <div class="esquerda flex-column" style="margin-left: 12px;">
                                <div class="esquerda top" style="
                            width: 200px;
                            font-family:'Jost';
                            font-size: 15px;
                            font-style: normal;
                            font-weight: 300;
                            text-decoration: none;
                            border: 1px solid #ECE8EF;
                            border-radius: 5px;
                            color: black;
                            text-align:center;
                            margin-bottom: 15px;
                            ">
                                    @item.Categoria.Nome.ToUpper()
                                </div>
                                <div class="esquerda bottom flex-col">
                                    <div class="imagem esquerda bottom">
                                        @Html.HiddenFor(m => item.LogotipoMimeType)
                                        @Html.HiddenFor(m => item.Logotipo)
                                        @Html.HiddenFor(m => item.NomeArquivo)
                                        @Html.HiddenFor(m => item.TamanhoArquivo)
                                        <img src="@Url.Action("GetLogotipo", "Cursos", new { id = item.CursoId })" width="200" height="150" />
                                    </div>
                                    <div class="texto esquerda bottom" style="margin-left: 15px;">
                                        <h3 style="font-family:'Jost'; font-size: 20px; font-weight: 600; margin: 0px 0px 5px 0px;">@item.Nome</h3>
                                        <h4 style="font-family:'Jost'; font-size: 16px; font-weight: 400; margin: 0px;">feito por @item.Professor.Nome</h4>
                                    </div>
                                </div>
                            </div>

                            <div class="direita" style="position:relative;">
                                @*<a href="/Avaliacoes/Create?AlunoId=@Model.MeusCursosIndexId?CursoId=@item.CursoId"> AVALIE</a>*@
                                <a href="@Url.Action("Create", "Avaliacoes", new { AlunoId = Model.MeusCursosIndexId, CursoId = item.CursoId})" style="
                            background-color: #FFEB82;
                            color: black;
                            font-weight: 600;
                            padding: 10px 1.6em;
                            top: 35%;
                            right: 10%;
                            position: absolute;
                            border-radius: 10px;
                            margin-right: 40px;
                            font-family: 'Jost';
                            font-size: 18px;
                            "> AVALIE</a>
                            </div>

                        </div>

                    </div>

                }

            </div>




        </div>

    </div>
    @Html.Partial("~/Views/Shared/_Footer.cshtml", Model)
    <script src="~/Scripts/scripts/slider.js"></script>
</body>
</html>

Stack_Learn/Views/Cursos/View.cshtml
@model IEnumerable<Modelos.Models.Curso>
@foreach (var item in Model)
{
    if (item.CategoriaId == @ViewBag.Categoria)
    {
        <a href="/Cursos/Details/@item.CursoId" class="flex-column center space-around" style="        
        padding: 2em;
        width: 225px;
        height: 300px;
        border: 3px solid transparent;
        box-shadow: 2px 1000px 1px #ffff inset;
        background-image: linear-gradient(to right, #70D7C7, #FFCB34);
        color: black;
        margin: 0px 12px 0px 12px;

        ">
            <img src="~/img/foto-card.svg" height="150" width="150" />
            <h3 class="fontJost400" style="height: 200px;">@item.Nome.ToUpper()</h3>
            <h3 class="fontJost400" style="background-color:#FFCC36; padding: 5px;">R$ @item.Preco</h3>
        </a>
    }
}