Stack_Learn/Controllers/CursosController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Stack_Learn.Context;
using Modelos.Models;
using System.IO;
using Stack_Learn.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Stack_Learn.Areas.Seguranca.Models;
using Stack_Learn.Infraestrutura;

namespace Stack_Learn.Controllers
{
    public class CursosController : Controller
    {

        private EFContext context = new EFContext();

        private GerenciadorUsuario GerenciadorUsuario
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<GerenciadorUsuario>();
            }
        }

        private void PopularViewBag(Curso curso = null)
        {
            if (curso == null)
            {
                ViewBag.CategoriaId = new SelectList(context.Categorias.OrderBy(b => b.Nome), "CategoriaId", "Nome", curso.CategoriaId);
                ViewBag.ProfessorId = new SelectList(context.Professores.OrderBy(b => b.Nome), "ProfessorId", "Nome", curso.ProfessorId);
            }
            else
            {
                ViewBag.CategoriaId = new SelectList(context.Categorias.OrderBy(b => b.Nome), "CategoriaId", "Nome", curso.CategoriaId);
                ViewBag.ProfessorId = new SelectList(context.Professores.OrderBy(b => b.Nome), "ProfessorId", "Nome", curso.ProfessorId);
            }


        }
        private byte[] SetLogotipo(HttpPostedFileBase logotipo)
        {
            var bytesLogotipo = new byte[logotipo.ContentLength];
            logotipo.InputStream.Read(bytesLogotipo, 0, logotipo.ContentLength);
            return bytesLogotipo;
        }
        public FileContentResult GetLogotipo(long id)
        {
            Curso curso = context.Cursos.Where(p => p.CursoId == id).Include(c => c.Categoria).Include(f => f.Professor).First();
            if (curso != null)
            {
                if (curso.NomeArquivo != null)
                {
                    var bytesLogotipo = new byte[curso.TamanhoArquivo];
                    FileStream fileStream = new FileStream(Server.MapPath("~/App_Data/" + curso.NomeArquivo), FileMode.Open, FileAccess.Read);
                    fileStream.Read(bytesLogotipo, 0, (int)curso.TamanhoArquivo);
                    return File(bytesLogotipo, curso.LogotipoMimeType);
                }
            }
            return null;
        }
        public ActionResult DownloadArquivo(long id)
        {

            Curso curso = context.Cursos.Where(p => p.CursoId == id).Include(c => c.Categoria).Include(f => f.Professor).First();
            FileStream fileStream = new FileStream(Server.MapPath("~/App_Data/" + curso.NomeArquivo), FileMode.Open, FileAccess.Read);
            return File(fileStream.Name, curso.LogotipoMimeType, curso.NomeArquivo);

        }
        private ActionResult GravarCurso(Curso curso, HttpPostedFileBase logotipo, string chkRemoverImagem)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (chkRemoverImagem != null)
                    {
                        curso.Logotipo = null;
                    }
                    if (logotipo != null)
                    {
                        curso.LogotipoMimeType = logotipo.ContentType;
                        curso.Logotipo = SetLogotipo(logotipo);
                        curso.NomeArquivo = logotipo.FileName;
                        curso.TamanhoArquivo = logotipo.ContentLength;

                        string strFileName = Server.MapPath("~/App_Data/") + Path.GetFileName(logotipo.FileName);
                        logotipo.SaveAs(strFileName);
                    }
                    if (curso.CursoId == null)
                    {
                        context.Cursos.Add(curso);
                    }
                    else
                    {
                        context.Entry(curso).State = EntityState.Modified;
                    }
                    context.SaveChanges();
                    return RedirectToAction("Index");
                }
                PopularViewBag(curso);
                return View(curso);
            }
            catch
            {
                PopularViewBag(curso);
                return View(curso);
            }
        }
        [Authorize(Roles = "ADM")]
        public ActionResult Index()
        {
            return View(context.Cursos.Include(c => c.Categoria).Include(f => f.Professor).OrderBy(n => n.Nome));
        }
        public ActionResult Lista()//get, sem post
        {
            var Cursos_Usuarios = new CursosUsuarios();
            if (System.Web.HttpContext.Current.User.Identity.Name.ToString() != "")
            {
                var userid = System.Web.HttpContext.Current.User.Identity.GetUserId();
                Usuario user = GerenciadorUsuario.FindById(userid);
                Cursos_Usuarios.AlunoId = user.AlunoId;
            }
            var Cursos_totais = new List<Curso>();
            foreach (var item in context.Cursos.Include(c => c.Categoria).Include(f => f.Professor).OrderBy(n => n.Nome))
            {
                Cursos_totais.Add(item);
            }
            Cursos_Usuarios.Cursos = Cursos_totais;

            var Categorias_totais = new List<Categoria>();
            foreach (var item in context.Categorias.OrderBy(c => c.Nome))
            {
                Categorias_totais.Add(item);
            }
            Cursos_Usuarios.Categorias = Categorias_totais;
            return View(Cursos_Usuarios);
        }
        [Authorize(Roles = "Aluno")]
        public ActionResult MeusCursosIndex(long? id)
        {
            //aluno -> pedido ok -> curso ok
            long? AlunoId = id;//sempre o primeiro
            List<Curso> concluidoo = new List<Curso>();
            List<Curso> emm_andamento = new List<Curso>();

            IQueryable<Curso> todos = context.Cursos.Include(c => c.Categoria).Include(f => f.Professor).OrderBy(n => n.Nome);

            foreach (Curso item in todos)
            {
                int concluidos = 0;
                int percorrer_list = item.Qtd_Aulas ;//2
                int list_final = 0;//0 1 2 

                foreach(Aula subitem in item.Aulas)
                {
                    if(subitem.AlunoId == AlunoId)
                    {
                        list_final++;//1 2 3
                        if (subitem.TrueFalse == true)
                        {
                            concluidos++;//1
                        }
                        if (list_final == percorrer_list || list_final == item.Aulas.Count)//tem todas as aulas para serem analisadas x se só tem uma
                        {
                            if (concluidos < percorrer_list)
                            {
                                emm_andamento.Add(item);
                            }
                            if (concluidos == percorrer_list)
                            {
                                concluidoo.Add(item);
                            }
                        }
                    }
                }
            }

            MeusCursosIndex index = new MeusCursosIndex();
            index.em_andamento = emm_andamento;
            index.concluido = concluidoo;
            index.MeusCursosIndexId = AlunoId;
            return View(index);


       }
        [Authorize(Roles = "ADM")]
        public ActionResult Create()
        {
            //para quem comprar, vir com todos os cursos falso
            ViewBag.CategoriaId = new SelectList(context.Categorias.OrderBy(b => b.Nome),"CategoriaId", "Nome");
            ViewBag.ProfessorId = new SelectList(context.Professores.OrderBy(b => b.Nome),"ProfessorId", "Nome");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Curso curso)
        {
            
            if (curso.Professor != null)
            {
                curso.NomeProfessor = curso.Professor.Nome;
            }
            else
            {
                curso.NomeProfessor = "Sem Professor";
            }
            context.Cursos.Add(curso);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        [Authorize(Roles = "ADM")]
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Curso curso = context.Cursos.Find(id);
            if (curso == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoriaId = new SelectList(context.Categorias.OrderBy(b => b.Nome), "CategoriaId","Nome", curso.CategoriaId);
            ViewBag.ProfessorId = new SelectList(context.Professores.OrderBy(b => b.Nome), "ProfessorId","Nome", curso.ProfessorId);
            return View(curso);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Curso curso, HttpPostedFileBase logotipo = null, string chkRemoverImagem = null)
        {
            return GravarCurso(curso, logotipo, chkRemoverImagem);
        }

        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Curso curso = context.Cursos.Where(p => p.CursoId == id).Include(c => c.Categoria).Include(f => f.Professor).First();
            if (curso == null)
            {
                return HttpNotFound();
            }
            CursoDetails objeto = new CursoDetails();
            objeto.curso = curso;
            objeto.cursos = context.Cursos.Include(c => c.Categoria).Include(f => f.Professor).OrderBy(n => n.Nome);
            
            var Cursos_Usuarios = new CursosUsuarios();

Stack_Learn/Controllers/PedidosController.cs
using Stack_Learn.Context;
using Modelos.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Stack_Learn.Areas.Seguranca.Models;
using Stack_Learn.Infraestrutura;

namespace Stack_Learn.Controllers
{
    public class PedidosController : Controller
    {
        private EFContext context = new EFContext();
        private GerenciadorUsuario GerenciadorUsuario
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<GerenciadorUsuario>();
            }
        }
        [Authorize(Roles = "ADM")]
        public ActionResult Index()
        {
            return View(context.Pedidos.Include(a=>a.Aluno).OrderBy(c => c.PedidoId));
        }
        [Authorize(Roles = "ADM")]
        public ActionResult IndexCanalha()
        {
            return View(context.Pedidos.Include(a => a.Aluno).OrderBy(c => c.PedidoId));
        }
        [Authorize(Roles = "ADM")]
        public ActionResult Create()
        {
            ViewBag.AlunoId = new SelectList(context.Alunos.OrderBy(b => b.Nome), "AlunoId", "Nome");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Pedido pedido)
        {
            context.Pedidos.Add(pedido);
            context.SaveChanges();
            return RedirectToAction("IndexCanalha");
        }
        [Authorize(Roles = "ADM")]
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pedido pedido = context.Pedidos.Find(id);
            if (pedido == null)
            {
                return HttpNotFound();
            }
            ViewBag.AlunoId = new SelectList(context.Alunos.OrderBy(b => b.Nome), "AlunoId", "Nome", pedido.Aluno);
            return View(pedido);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Pedido pedido)
        {
            if (ModelState.IsValid)
            {
                context.Entry(pedido).State = EntityState.Modified;
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(pedido);
        }
        [Authorize(Roles = "ADM")]
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pedido pedido = context.Pedidos.Where(f => f.PedidoId == id).Include(a=>a.Aluno).First();
            if (pedido == null)
            {
                return HttpNotFound();
            }
            return View(pedido);
        }
        [Authorize(Roles = "ADM")]
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pedido pedido = context.Pedidos.Where(p => p.PedidoId == id).Include(c => c.Aluno).First();
            if (pedido == null)
            {
                return HttpNotFound();
            }
            return View(pedido);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(long id)
        {
            Pedido pedido = context.Pedidos.Find(id);
            context.Pedidos.Remove(pedido);
            context.SaveChanges();
            TempData["Message"] = "Pedidos " + pedido.PedidoId + " foi removido";
            return RedirectToAction("Index");
        }
        [Authorize(Roles = "Aluno")]
        public ActionResult CarrrinhoCompra(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pedido pedido = context.Pedidos.Find(id);
            if (pedido == null)
            {
                return HttpNotFound();
            }
            ViewBag.AlunoId = new SelectList(context.Alunos.OrderBy(b => b.Nome), "AlunoId", "Nome", pedido.Aluno);
            Console.WriteLine(pedido.Cursos);
            pedido.Valor_Total = 0;
            if(pedido.Cursos.Count() > 0)
            {
                foreach (Curso curso in pedido.Cursos)
                {
                    pedido.Valor_Total = pedido.Valor_Total + curso.Preco;
                }
            }
            var CursosUsuarios = new CursosUsuarios();
            CursosUsuarios.AlunoId = pedido.AlunoId;
            CursosUsuarios.CursosUsuariosId = pedido.AlunoId;
            pedido.curso_usuario = CursosUsuarios;

            return View(pedido);
        }


        [HttpPost]
        public ActionResult CarrrinhoCompra(Pedido pedido)
        {
            if (ModelState.IsValid)
            {
                /*
                Aluno 1, pedido pago -> aula 1 false 1, aula 2 false 1, aula 3 false 1
                aulaDetails.AulaId = id.Value;
                aulaDetails.Ordem = aula.Ordem;
                aulaDetails.Titulo = aula.Titulo;
                aulaDetails.Duracao = aula.Duracao;
                aulaDetails.CursoId = aula.CursoId;
                aulaDetails.Curso = aula.Curso;
                aulaDetails.Curso.Categoria = aula.Curso.Categoria;
                */

                Pedido pedido2 = context.Pedidos.Find(pedido.PedidoId);
                pedido2.Pago = true;
                pedido2.Data_Pagamento = DateTime.Now;
                context.Entry(pedido2).State = EntityState.Modified;
                Conclusao conclusao_false = new Conclusao();
                foreach (var conclusao in context.Conclusoes.Include(c => c.Aluno))
                {
                    if (conclusao.Concluido == false && conclusao.AlunoId == pedido2.AlunoId)
                    {
                        conclusao_false = conclusao;
                    }
                }
                foreach (var curso in pedido2.Cursos)
                {
                    foreach (var aula in curso.Aulas)
                    {
                        Aula aula_adicionar = new Aula();
                        aula_adicionar = aula;
                        aula_adicionar.AlunoId = pedido2.AlunoId;
                        aula_adicionar.Conclusao = conclusao_false;
                        aula_adicionar.ConclusaoId = conclusao_false.ConclusaoId;
                        context.Aulas.Add(aula_adicionar);
                    }
                }
                pedido2.Cursos.Clear();

                context.SaveChanges();
                return RedirectToAction("../Home/PaginaInicial");
            }
            return View(pedido);
        }

        [HttpPost]
        public ActionResult ExcluirCurso(long item_CursoId)
        {
            Curso curso = context.Cursos.Where(i => i.CursoId == item_CursoId).First();
            var userid = System.Web.HttpContext.Current.User.Identity.GetUserId();
            Usuario user = GerenciadorUsuario.FindById(userid);
            Pedido pedido = context.Pedidos.Where(p => p.PedidoId == user.AlunoId).First();
            long id = pedido.PedidoId;
            pedido.Cursos.Remove(curso);
            context.SaveChanges();
            return RedirectToAction("CarrrinhoCompra", new { id = id });
        }
    }
}

Stack_Learn/Views/Pedidos/CarrrinhoCompra.cshtml
@model Modelos.Models.Pedido

@{
    long x = Model.Cursos.Count();
    ViewBag.Title = "CarrinhoCompra";
    Layout = null;
}


@if (Model.AlunoId == null)
{
    @Html.Partial("~/Views/Shared/_Header_Sem_Login.cshtml", Model)
}
else
{
    @Html.Partial("~/Views/Shared/_Header_Aluno.cshtml", Model.curso_usuario)
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/Css/CarrinhoPagamento.css">
    <script src="~/Scripts/scripts/script.js" defer></script>
    <title>Meu Carrinho</title>
</head>
@using (Html.BeginForm("CarrrinhoCompra", "Pedidos", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.HiddenFor(model => model.PedidoId)
    <body>
        <div class="body-carrinho">
            <div class="conteiner-bar">

                <div class="bar">


                    <div class="itens-bar ">


                        <p>Carrinho</p>
                        <div data-title="carrinho" class="bolacheck step"></div>


                    </div>
@*                     <div class="itens-bar">

                        <p>Identificação</p>
                        <div data-title="login" class="bolauncheck step"></div>

                    </div> *@
                    <div class="itens-bar">

                        <p>Pagamento</p>
                        <div data-title="pagamento" class="bolauncheck step"></div>

                    </div>

                </div>
                <div>
                    <div class="progresso-area">
                        <div class="progresso" id="progress"></div>
                    </div>
                </div>
            </div>
            <div class="form-step form-step-active" style="margin: 0 10%;">
                <div class="cursos-carrinho">
                    <p><strong>MEU CARRINHO</strong></p>
                    <div class="flex-carrinho line-border" style="padding: 1em 0 1em 0;">
                        <p style="width: 9em; text-align: center;"><spancolor>PRODUTO</spancolor> </p>
                        <div class="flex-carrinho dados-nome" style="width: 100%;">
                            <div style="width: 50%;"></div>
                            <div style="width: 30%;">
                                <p class=""><spancolor>PREÇO</spancolor> </p>
                            </div>

                            <div style="width: 5%;"></div>
                        </div>

                    </div>

                    @Html.Partial("~/Views/Pedidos/_Carrinho_Curso.cshtml", Model.Cursos)
                </div>

                <aside class="aside">
                    <p class="line-border-aside m-1"><strong>RESUMO DO PEDIDO</strong> </p>
                    <p class="line-border-aside m-1">@x CURSOS</p>
                    <div class="flex-carrinho m-1">
                        <p>TOTAL</p>
                        <div style="text-align: right;">
                            <p><strong>R$ @Html.DisplayFor(modalItem => Model.Valor_Total)</strong> </p>
                            <p><span>ou 12x de x.00</span> </p>
                        </div>
                    </div>
                    <div class="flex-carrinho" style="justify-content: center;">
                        @if (x > 0)
                        {
                            <a class="btn-prev-next btn-next">
                                CONTINUAR
                            </a>
                        }
                        else
                        {
                            <a class="btn-prev-next" style="filter:opacity(0.5); cursor: default;">
                                CONTINUAR
                            </a>
                        }
                    </div>

                </aside>
            </div>
@*             <div class="login form-step ">
                <div>
                    <div style="text-align: center;">
                        <h2>LOGIN</h2>
                    </div>

                    <form action="">
                        <div>
                            <label for="login">login</label>
                            <br>
                            <input id="email" type="text">
                        </div>
                        <div>
                            <label for="senha">senha</label>
                            <br>
                            <input id="senha" type="password">
                        </div>
                    </form>
                    <div class="btn-group">
                        <a class="btn-prev-next btn-prev">
                            VOLTAR
                        </a>

                        <a class="btn-prev-next btn-next">
                            CONTINUAR
                        </a>
                    </div>
                </div>

            </div> *@
            <div class="form-step" style="flex-direction: column;">
                <div class="pagamento ">
                    <div style="text-align: center;">
                        <h2>Pagamento</h2>
                    </div>
                    <div class="flex-carrinho" style="gap: 4em;">
                        <div>
                            <div>
                                <form action="">
                                    <div>
                                        <label for="login">Nome Completo</label>
                                        <br>
                                        <input id="email" type="text" class="input-payment">
                                    </div>
                                    <div>
                                        <label for="senha">Número do Cartão</label>
                                        <br>
                                        <input id="senha" type="text" class="input-payment">
                                    </div>
                                    <div class="flex-carrinho">
                                        <div>
                                            <label for="val">Validade</label>
                                            <br>
                                            <input id="val" type="text" class="input-payment-half">
                                        </div>
                                        <div style="margin-left: 2em;">
                                            <label for="cvv">CVV</label>
                                            <br>
                                            <input id="cvv" type="password" class="input-payment-half">
                                            <button class="checkpass" onclick="showCvv()" id="icon"></button>
                                        </div>
                                    </div>
                                </form>
                                <div class="" style="margin-top: 2em;">
                                    <a class="btn-prev-next btn-prev">
                                        VOLTAR
                                    </a>

                                </div>
                            </div>
                        </div>

                        <div>
                            <figure>
                                <img src="~/Fts/cartao.svg" alt="">
                                <img src="~/Fts/art1.svg" class="art-pagamento">
                            </figure>
                        </div>
                        <br>


                    </div>
                </div>
                <div class="flex-carrinho" style="justify-content: center; margin-top: 5em;">
                    <input type="submit" value="COMPRAR" class="btn-prev-next" style="height: 50px;"/>

                </div>
            </div>
        </div>
        <div class="footer">@Html.Partial("~/Views/Shared/_Footer.cshtml", Model)</div>
</body>
}
</html>

Stack_Learn/Views/Pedidos/Create.cshtml
@model Modelos.Models.Pedido

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pedido</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Pago, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Pago)
                    @Html.ValidationMessageFor(model => model.Pago, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cancelamento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Cancelamento)
                    @Html.ValidationMessageFor(model => model.Cancelamento, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Data_cancelamento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Data_cancelamento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Data_cancelamento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Data_Pagamento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Data_Pagamento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Data_Pagamento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Valor_Total, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Valor_Total, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Valor_Total, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AlunoId, "AlunoId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AlunoId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AlunoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Stack_Learn/Views/Pedidos/Index.cshtml
@model IEnumerable<Modelos.Models.Pedido>
@{
    Layout = null;
    var a = 0;
}
<head>
    <title>Stack Learn | Lista comprados</title>
    <link href="@Url.Content("~/Css/PaginasInternas.css")" rel="stylesheet" />
</head>
<body>
    @foreach (var item in Model)
    {
        a = a + 1;
        if (a < 2)
                {
            @Html.Partial("~/Views/Shared/_Header_Aluno.cshtml", item.curso_usuario)
                }
    }
    
    <h1 class="fontJost400" style="background-color:#FFCC36; margin-top:0px; font-size:24px; text-align:center; padding: 1.5em; margin-bottom: 2em;">MEUS CURSOS</h1>

    <div class="part1">

    </div>
    <div class="part2" style="background-color: #454545;">

    </div>
    @Html.Partial("~/Views/Shared/_Footer.cshtml", Model)
</body>
@section ScriptPage{
    <script src="@Url.Content("~/scripts/DataTables-1.10.2/jquery.dataTables.js")"></script>
    <script src="@Url.Content("~/scripts/DataTables-1.10.2/dataTables.bootstrap.js")"></script>
}

Stack_Learn/Views/Pedidos/_Carrinho_Curso.cshtml
@model IEnumerable<Modelos.Models.Curso>

@{
    Layout = null;
}

@foreach (var item in Model)
{
    



<div class="flex-carrinho line-border">
    <figure>
        <img src="@Url.Action("GetLogotipo", "Cursos", new { id = item.CursoId })" alt="" class="curso">
    </figure>
    <div class="flex-carrinho dados-curso">
        <div style="width: 50%;">
            <p><strong>@Html.DisplayFor(modalItem => item.Nome)</strong></p>
            <p style="margin-top: 1em;">
                <spancolor>
                    @Html.DisplayFor(modalItem => item.NomeProfessor)
                </spancolor>
            </p>
        </div>
        <div style="width: 30%;">
            <p>
                <strong>
                    R$ @Html.DisplayFor(modelItem => item.Preco)
                </strong>
            </p>
        </div>
        <div style="width: 5%;">
            @using (Html.BeginForm("ExcluirCurso", "Pedidos", new { item_CursoId = item.CursoId }))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(modelItem => item.CursoId)
                <input id="input-excluir-curso" type="submit" value="X" class="strong excluir-compra" />
            }
        </div>
    </div>
</div>
                }